runtime: nodejs18
env: standard

env_variables:
  # Server Configuration
  PORT: "8080"

  # Database Configuration (PostgreSQL – Cloud SQL)
  DB_HOST: "YOUR_CLOUD_SQL_PUBLIC_IP"
  DB_PORT: "5432"
  DB_NAME: "spotit_db"
  DB_USER: "postgres"
  DB_PASS: "your_password"

  # Authentication
  JWT_SECRET: "your_jwt_secret_key_change_this"
  GOOGLE_CLIENT_ID: "your_google_client_id.apps.googleusercontent.com"

  # Email Service (SMTP)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your_email@gmail.com"
  SMTP_PASSWORD: "your_app_password"

  # Admin Seeder Defaults
  ADMIN_EMAIL: "admin@spotit.com"
  ADMIN_PASSWORD: "admin_secure_password"